-- 코드를 입력하세요
SELECT
    AA.NAME
    , AA.DATETIME
FROM  
    (
        SELECT I.NAME, I.DATETIME FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O ON (I.ANIMAL_ID = O.ANIMAL_ID)
        WHERE 1=1
            AND NOT EXISTS (SELECT 1 FROM ANIMAL_OUTS WHERE ANIMAL_ID = I.ANIMAL_ID)   
        ORDER BY I.DATETIME
    ) AA
WHERE 1=1
    AND ROWNUM <= 3