-- 코드를 입력하세요
SELECT
    GS.USER_ID
    , GS.NICKNAME
    , SUM(GB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD GB RIGHT JOIN USED_GOODS_USER GS ON GB.WRITER_ID = GS.USER_ID
WHERE 1=1
    AND GB.STATUS = 'DONE'
GROUP BY
    GS.USER_ID
    , GS.NICKNAME
HAVING 
  SUM(GB.PRICE) >= 700000
ORDER BY    
    SUM(GB.PRICE) 