-- 코드를 입력하세요
SELECT
    DISTINCT(CAR_ID) AS CAR_ID
FROM 
    CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CS USING (CAR_ID)
WHERE 1=1
    AND CAR_TYPE = '세단'
    AND TO_CHAR(CS.START_DATE, 'MM') = '10'
ORDER BY
    CAR_ID DESC