-- 코드를 입력하세요
SELECT
    B.CATEGORY
    , SUM(BS.SALES) AS TOTAL_SALES
FROM
    BOOK B RIGHT JOIN BOOK_SALES BS ON (B.BOOK_ID = BS.BOOK_ID)
WHERE 1=1
    AND TO_CHAR(BS.SALES_DATE, 'YYYYMMDD') LIKE '202201%'
GROUP BY
    B.CATEGORY
ORDER BY   
    B.CATEGORY